{% set name = "cuda-compat" %}
{% set driver_version = "555.42.06" %}
{% set cuda_version = "12.5.1" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set extension = "tar.xz" %}  # [not win]

package:
  name: {{ name|lower }}
  version: {{ cuda_version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/nvidia_driver/{{ platform }}/nvidia_driver-{{ platform }}-{{ driver_version }}-archive.{{ extension }}
  sha256: 944a7b3c30265f440fe8d2d2579fca82a2bd01431d4ad3ab43f9a03725a0c447  # [linux64]
  sha256: a764c03c9be66fb35144ec23aafa7cf73f9d392fced38db982c32ac53f997a7d  # [aarch64]

build:
  number: 0
  skip: true  # [osx or win or ppc64le]
  script_env:
    - DRV_VERSION={{ driver_version }}

outputs:
  - name: cuda-compat
    requirements:
      run:
        - {{ pin_subpackage("cuda-compat-impl", exact=True) }}
    test:
      commands:
        - exit 0
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA Compatibility Platform
      description: |
          Package containing all the necessary CUDA driver files related to forward
          compatibility. This compatibility enables newer CUDA runtimes to work with
          older display drivers. Used for Tesla cards only.
      doc_url: https://docs.nvidia.com/cuda/index.html

  - name: cuda-compat-impl
    version: {{ driver_version }}
    files:
      - cuda-compat
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
    test:
      commands:
        - test -f $PREFIX/cuda-compat/libcuda.so.{{ driver_version }}
        - test -L $PREFIX/cuda-compat/libcuda.so.1
        - test -L $PREFIX/cuda-compat/libcuda.so
        - test -f $PREFIX/cuda-compat/libnvidia-nvvm.so.{{ driver_version }}
        - test -L $PREFIX/cuda-compat/libnvidia-nvvm.so.4
        - test -L $PREFIX/cuda-compat/libnvidia-nvvm.so
        - test -f $PREFIX/cuda-compat/libnvidia-ptxjitcompiler.so.{{ driver_version }}
        - test -L $PREFIX/cuda-compat/libnvidia-ptxjitcompiler.so.1
        - test -f $PREFIX/cuda-compat/libcudadebugger.so.{{ driver_version }}
        - test -L $PREFIX/cuda-compat/libcudadebugger.so.1
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA Compatibility Platform
      description: |
          Package containing all the necessary CUDA driver files related to forward
          compatibility. This compatibility enables newer CUDA runtimes to work with
          older display drivers. Used for Tesla cards only.
      doc_url: https://docs.nvidia.com/cuda/index.html

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: CUDA Compatibility Platform
  description: |
      Package containing all the necessary CUDA driver files related to forward
      compatibility. This compatibility enables newer CUDA runtimes to work with
      older display drivers. Used for Tesla cards only.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
