{% set name = "cuda-compat" %}
{% set driver_version = "550.54.15" %}
{% set cuda_version = "12.4.1" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set extension = "tar.xz" %}  # [not win]

package:
  name: {{ name|lower }}
  version: {{ cuda_version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/nvidia_driver/{{ platform }}/nvidia_driver-{{ platform }}-{{ driver_version }}-archive.{{ extension }}
  sha256: e1416ebc1e7b4a14d393ca584e3f9c5e22f9750f4ba502a8ba2c5c5ad943bbb5  # [linux64]
  sha256: ae53576c73f16084f3975aad254ee756e524525b1ca6d72d49d6e4b33083d818  # [ppc64le]
  sha256: b39a8cb837fe3846284d89ab2202e93b14804349d3fc9aa8a8384fd2759ec2f5  # [aarch64]

build:
  number: 2
  skip: true  # [osx or win]
  script_env:
    - DRV_VERSION={{ driver_version }}

outputs:
  - name: cuda-compat
    requirements:
      run:
        - {{ pin_subpackage("cuda-compat-impl", exact=True) }}
    test:
      commands:
        - exit 0
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA Compatibility Platform
      description: |
          Package containing all the necessary CUDA driver files related to forward
          compatibility. This compatibility enables newer CUDA runtimes to work with
          older display drivers. Used for Tesla cards only.
      doc_url: https://docs.nvidia.com/cuda/index.html

  - name: cuda-compat-impl
    version: {{ driver_version }}
    files:
      - cuda-compat
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
    test:
      commands:
        - test -f $PREFIX/cuda-compat/libcuda.so.{{ driver_version }}
        - test -L $PREFIX/cuda-compat/libcuda.so.1
        - test -L $PREFIX/cuda-compat/libcuda.so
        - test -f $PREFIX/cuda-compat/libnvidia-nvvm.so.{{ driver_version }}
        - test -L $PREFIX/cuda-compat/libnvidia-nvvm.so.4
        - test -L $PREFIX/cuda-compat/libnvidia-nvvm.so
        - test -f $PREFIX/cuda-compat/libnvidia-ptxjitcompiler.so.{{ driver_version }}
        - test -L $PREFIX/cuda-compat/libnvidia-ptxjitcompiler.so.1
        - test -f $PREFIX/cuda-compat/libcudadebugger.so.{{ driver_version }}
        - test -L $PREFIX/cuda-compat/libcudadebugger.so.1
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA Compatibility Platform
      description: |
          Package containing all the necessary CUDA driver files related to forward
          compatibility. This compatibility enables newer CUDA runtimes to work with
          older display drivers. Used for Tesla cards only.
      doc_url: https://docs.nvidia.com/cuda/index.html

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: CUDA Compatibility Platform
  description: |
      Package containing all the necessary CUDA driver files related to forward
      compatibility. This compatibility enables newer CUDA runtimes to work with
      older display drivers. Used for Tesla cards only.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
